version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "07:00"
    groups:
      dependencies:
        patterns:
          - "*"
